### ISSUE TITLE
Install failed in Linux

### ISSUE THREAD

**Issue by hardass** [weigj/go-odbc#15]
display missing sql.h when installing. would you please advise? Thanks.

Message:

localhost odbc # go install
# odbc

odbc.go:18:17: fatal error: sql.h: No such file or directory
compilation terminated.

**Comment by Canop** [comment]
I got the same exact problem with the clone I just made, would it be possible to know how it was solved ?

**Comment by xXPhenomXx** [comment]
sudo yum install unixODBC-devel
